- finales_tenant_uuid: ad771155-97b9-46e9-92bd-5e9b2c378a0a
  archive_accounts:
    - domain_name: archive.big-map.eu
      email_address: francois.liot+FINALES_tenant_1@epfl.ch
      token:
    - domain_name: big-map-archive-demo.materialscloud.org
      email_address: francois.liot+FINALES_tenant_1@epfl.ch
      token:
- finales_tenant_uuid: e0262ca0-c546-4e9a-a4a1-5ea6cb9b1e13
  archive_accounts:
    - domain_name: archive.big-map.eu
      email_address: francois.liot+FINALES_tenant_2@epfl.ch
      token:
    - domain_name: big-map-archive-demo.materialscloud.org
      email_address: francois.liot+FINALES_tenant_2@epfl.ch
      token: